---
- name: Backup Databases and Upload to Azure Blob
  hosts: all
  vars:
    current_date: "{{ lookup('pipe', 'date +%b-%d_') }}"
    backup_base_path: "/tmp/{{ current_date }}DB_Backup"
    azure_blob_sas_url_mysql: "https://prodmobiusdbbkp.blob.core.windows.net/mysqlmanaged?sv=2022-11-02&ss=bfqt&srt=sco&sp=rwdlacupiytfx&se=2043-10-20T01:01:06Z&st=2023-10-19T17:01:06Z&spr=https&sig=3agOLgIiDfK9DFCu%2Fx3WwCBq%2BEExHWExCoOEhA09Dgs="
    azure_blob_sas_url_mongodb: "https://prodmobiusdbbkp.blob.core.windows.net/mongodb?sv=2022-11-02&ss=bfqt&srt=sco&sp=rwdlacupiytfx&se=2043-10-20T01:01:06Z&st=2023-10-19T17:01:06Z&spr=https&sig=3agOLgIiDfK9DFCu%2Fx3WwCBq%2BEExHWExCoOEhA09Dgs="
    azure_blob_sas_url_postgres: "https://prodmobiusdbbkp.blob.core.windows.net/postgresdb?sv=2022-11-02&ss=bfqt&srt=sco&sp=rwdlacupiytfx&se=2043-10-20T01:01:06Z&st=2023-10-19T17:01:06Z&spr=https&sig=3agOLgIiDfK9DFCu%2Fx3WwCBq%2BEExHWExCoOEhA09Dgs="

  tasks:
    - name: Create backup directory structure
      ansible.builtin.file:
        path: "{{ backup_base_path }}/{{ item }}"
        state: directory
      loop:
        - mysql
        - mongo
        - psql

    - name: Dump MySQL databases
      shell: |
        USER="mysql"
        PASSWORD="Gaian-M0bIusP#9Pr0d"
        HOST="mobius-prod-mysql-new-flexible-server.mysql.database.azure.com"
        databases=$(mysql -u $USER -p"$PASSWORD" -h $HOST -e "SHOW DATABASES;" | tr -d "| " | grep -v Database)
        for db in $databases; do
          if [[ "$db" != "information_schema" ]] && [[ "$db" != "performance_schema" ]] && [[ "$db" != "mysql" ]] && [[ "$db" != "sys" ]] && [[ "$db" != _* ]] ; then
            echo "Dumping database: $db"
            mysqldump -u $USER -p"$PASSWORD" -h $HOST --set-gtid-purged=OFF --skip-lock-tables --databases "$db" > "{{ backup_base_path }}/mysql/$db.sql"
          fi
        done
      args:
        executable: /bin/bash
      become: true

    - name: Dump MongoDB databases
      shell: mongodump --uri="mongodb://mobiusprod:Kh3M459za*GMGb@172.16.8.6:27017,172.16.8.40:27017,172.16.8.41:27017/?authSource=admin&replicaSet=my_mongodb_0" --out="{{ backup_base_path }}/mongo/"
      become: true

    - name: Dump PostgreSQL databases
      shell: |
        pg_dump -h mobius-prod-postgres-flexible-server.postgres.database.azure.com -U mobius -Ft targettingframework -f "{{ backup_base_path }}/psql/targettingframework_backup.tar"
        echo "Gaian$%Mobiu$Pr0d" | pg_dump -h mobius-prod-postgres-flexible-server.postgres.database.azure.com -U mobius -Ft grafana -f "{{ backup_base_path }}/psql/grafana_backup.tar"
      become: true
      environment:
        PGPASSWORD: "Gaian$%Mobiu$Pr0d"

    - name: Create tarballs of each database backup
      shell: tar -czvf "{{ backup_base_path }}_{{ item.key }}_backup.tar.gz" -C "{{ backup_base_path }}" "{{ item.value }}"
      loop:
        - { key: "mysql", value: "mysql" }
        - { key: "mongo", value: "mongo" }
        - { key: "psql", value: "psql" }
      become: true

    - name: Upload MySQL backup to Azure Blob using azcopy
      shell: azcopy copy '{{ backup_base_path }}_mysql_backup.tar.gz' '{{ azure_blob_sas_url_mysql }}' --recursive=true
      become: true

    - name: Upload MongoDB backup to Azure Blob using azcopy
      shell: azcopy copy '{{ backup_base_path }}_mongo_backup.tar.gz' '{{ azure_blob_sas_url_mongodb }}' --recursive=true
      become: true

    - name: Upload PostgreSQL backup to Azure Blob using azcopy
      shell: azcopy copy '{{ backup_base_path }}_psql_backup.tar.gz' '{{ azure_blob_sas_url_postgres }}' --recursive=true
      become: true
